### ISSUE TITLE
HowTo install...

### ISSUE THREAD

**Issue by m-gnaedig** [orchestracities/map-panel#62]
Hi

Your screenshots locks great ;-)

I am looking for a Grafana Map which can show some JSON values.
The Metric Key Value is a string in my case. Not a number.
It would also be cool to setup dynamic links to the map points.
I really like to test your solution. But I don't see an install instruction.

Thanks for any advice
Manfred

**Comment by chicco785** [comment]
hi @m-gnaedig
sorry we missed your message.
you can use the release content: https://github.com/orchestracities/grafana-map-plugin/releases/tag/v1.4.2
unzip in the plugin folder, and configure your grafana to load also unsigned plugins:
https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins

**Comment by johncaipa** [comment]
Hi, i get this error
![image](https://user-images.githubusercontent.com/31298276/160710362-f249d774-efde-41e7-9fee-41d7b1ce8388.png)
And on the logs console i get this, I don't see any errors regarding the plugin
![image](https://user-images.githubusercontent.com/31298276/160710860-db889df6-27c0-4fca-ac2c-997e7655bf72.png)

**Comment by chicco785** [comment]
@johncaipa my only guess is that you didn't configure the `allow_loading_unsigned_plugins` without error in the logs, hard to say :/

**Comment by chicco785** [comment]
@johncaipa i got my api key approved for community signature, i am gonna release v1.4.3 with that signature shortly

**Comment by chicco785** [comment]
here is the link to the new release: https://github.com/orchestracities/grafana-map-plugin/releases/download/v1.4.3/orchestracities-map-panel-1.4.3.zip

**Comment by chicco785** [comment]
@m-gnaedig @johncaipa 
the plugin is now officially supported by Grafana:
https://grafana.com/grafana/plugins/orchestracities-map-panel/

**Comment by johncaipa** [comment]
Hello @chicco785, sorry to keep bothering you with this, but I haven't been able to use it yet, this is what is in the docker installation log.
![image](https://user-images.githubusercontent.com/31298276/166288741-ae9e19a6-8742-4fae-a5f1-a7adced03285.png)

`✔ Downloaded orchestracities-map-panel v1.4.3 zip successfully
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
✔ Downloaded grafana-clock-panel v1.3.0 zip successfully
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
✔ Downloaded grafana-worldmap-panel v0.3.3 zip successfully
Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Starting Grafana" version=8.5.0 commit=6134e3cf35 branch=HEAD compiled=2022-04-21T10:36:58Z
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Config overridden from Environment variable" var="GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=orchestracities-map-panel"
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Path Data" path=/var/lib/grafana
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2022-05-02T16:31:40.52+0000 lvl=info msg="App mode production"
logger=sqlstore t=2022-05-02T16:31:40.52+0000 lvl=info msg="Connecting to DB" dbtype=sqlite3
logger=sqlstore t=2022-05-02T16:31:40.53+0000 lvl=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
logger=migrator t=2022-05-02T16:31:40.55+0000 lvl=info msg="Starting DB migrations"
logger=migrator t=2022-05-02T16:31:40.55+0000 lvl=info msg="migrations completed" performed=0 skipped=392 duration=683.3µs
logger=plugin.manager t=2022-05-02T16:31:40.58+0000 lvl=info msg="Plugin registered" pluginId=input
logger=plugin.signature.validator t=2022-05-02T16:31:40.64+0000 lvl=warn msg="Permitting unsigned plugin. This is not recommended" pluginID=orchestracities-map-panel pluginDir=/var/lib/grafana/plugins/grafana-map-plugin/src
logger=plugin.loader t=2022-05-02T16:31:40.64+0000 lvl=warn msg="Plugin missing module.js" pluginID=orchestracities-map-panel warning="Missing module.js, If you loaded this plugin from git, make sure to compile it." path=/var/lib/grafana/plugins/grafana-map-plugin/src/module.js
logger=plugin.manager t=2022-05-02T16:31:40.64+0000 lvl=info msg="Plugin registered" pluginId=grafana-clock-panel
logger=plugin.manager t=2022-05-02T16:31:40.64+0000 lvl=info msg="Plugin registered" pluginId=orchestracities-map-panel
logger=plugin.manager t=2022-05-02T16:31:40.64+0000 lvl=info msg="Plugin registered" pluginId=grafana-worldmap-panel
logger=plugin.manager t=2022-05-02T16:31:40.64+0000 lvl=eror msg="Could not start plugin" pluginId=orchestracities-map-panel err="plugin orchestracities-map-panel is already registered"
logger=query_data t=2022-05-02T16:31:40.65+0000 lvl=info msg="Query Service initialization"
logger=live.push_http t=2022-05-02T16:31:40.65+0000 lvl=info msg="Live Push Gateway initialization"
logger=grafanaStorageLogger t=2022-05-02T16:31:40.75+0000 lvl=info msg="storage starting"
logger=ngalert t=2022-05-02T16:31:40.75+0000 lvl=info msg="warming cache for startup"
logger=http.server t=2022-05-02T16:31:40.75+0000 lvl=info msg="HTTP Server Listen" address=[::]:3000 protocol=http subUrl= socket=
logger=ngalert.multiorg.alertmanager t=2022-05-02T16:31:40.76+0000 lvl=info msg="starting MultiOrg Alertmanager"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-02T16:31:51.52+0000 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=172.18.1.1 time_ms=8 duration=8.0197ms size=0 referer= traceID=00000000000000000000000000000000
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-02T16:32:27.28+0000 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=172.18.1.1 time_ms=1 duration=1.7495ms size=0 referer= traceID=00000000000000000000000000000000
logger=context userId=1 orgId=1 uname=admin t=2022-05-02T16:32:29.12+0000 lvl=eror msg="Plugin file not found" error="open /var/lib/grafana/plugins/grafana-map-plugin/src/module.js: no such file or directory" traceID=
logger=context userId=1 orgId=1 uname=admin t=2022-05-02T16:32:29.12+0000 lvl=info msg="Request Completed" method=GET path=/public/plugins/orchestracities-map-panel/module.js status=404 remote_addr=172.18.1.1 time_ms=1 duration=1.6188ms size=49 referer=http://localhost:3000/plugins/orchestracities-map-panel
logger=http.server t=2022-05-02T16:32:35.51+0000 lvl=info msg="Successful Logout" User=admin@localhost
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-02T16:32:35.51+0000 lvl=info msg="Request Completed" method=GET path=/logout status=302 remote_addr=172.18.1.1 time_ms=15 duration=15.3089ms size=29 referer=http://localhost:3000/plugins/orchestracities-map-panel traceID=00000000000000000000000000000000
logger=http.server t=2022-05-02T16:32:40.87+0000 lvl=info msg="Successful Login" User=admin@localhost
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-02T16:32:43.47+0000 lvl=info msg="Request Completed" method=GET path=/api/live/ws status=0 remote_addr=172.18.1.1 time_ms=1 duration=1.2885ms size=0 referer= traceID=00000000000000000000000000000000
logger=context userId=1 orgId=1 uname=admin t=2022-05-02T16:33:03.68+0000 lvl=eror msg="Plugin file not found" error="open /var/lib/grafana/plugins/grafana-map-plugin/src/module.js: no such file or directory" traceID=
logger=context userId=1 orgId=1 uname=admin t=2022-05-02T16:33:03.68+0000 lvl=info msg="Request Completed" method=GET path=/public/plugins/orchestracities-map-panel/module.js status=404 remote_addr=172.18.1.1 time_ms=0 duration=758.7µs size=49 referer=http://localhost:3000/plugins/orchestracities-map-panel
logger=tsdb.postgres t=2022-05-02T16:33:49.04+0000 lvl=eror msg="query error" err="dial tcp :5432: connect: connection refused"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-02T16:33:49.04+0000 lvl=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=172.18.1.1 time_ms=2 duration=2.1229ms size=1683 referer="http://localhost:3000/dashboard/new?orgId=1&editPanel=2" traceID=00000000000000000000000000000000
logger=tsdb.postgres t=2022-05-02T16:34:01.95+0000 lvl=eror msg="query error" err="dial tcp :5432: connect: connection refused"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-02T16:34:01.95+0000 lvl=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=172.18.1.1 time_ms=3 duration=3.6254ms size=1683 referer="http://localhost:3000/dashboard/new?orgId=1&editPanel=2&showCategory=Panel%20options" traceID=00000000000000000000000000000000
logger=tsdb.postgres t=2022-05-02T16:38:04.74+0000 lvl=eror msg="query error" err="dial tcp :5432: connect: connection refused"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-05-02T16:38:04.75+0000 lvl=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=172.18.1.1 time_ms=3 duration=3.0507ms size=284 referer=http://localhost:3000/datasources/edit/000000001 traceID=00000000000000000000000000000000`
