### ISSUE TITLE
Use "Value Mapping" colors

### ISSUE THREAD

**Issue by luizluca** [orchestracities/map-panel#75]
A mapped value color should be used instead the one from color scheme. This is how grafana geomap works.

**Comment by chicco785** [comment]
> A mapped value color should be used instead the one from color scheme. This is how grafana geomap works.

@luizluca can you explain what's the issue? I am not sure to understand it.

**Comment by chicco785** [comment]
i think i understood what you mean:
![image](https://user-images.githubusercontent.com/777218/187337205-f2c76420-9a62-42cc-a8bf-0782dfd5c4c3.png)

is this what you want to support?

**Comment by luizluca** [comment]
Yes. For example, I have a [0,1] progress's metric that uses red-yellow-green color scheme. However, I need to visually differ 0 (not started) from 0.0001 or 0.99999 from 1 (completed). With grafana core plugin, the mapped color have precedence and I can use purple or blue for 0 and 1.

**Comment by chicco785** [comment]
https://github.com/orchestracities/map-panel/tree/migrate-to-9.1.1 contains the fix, if you want to test it and confirm is all fine, refer to [CONTRIBUTING.md](https://github.com/orchestracities/map-panel/blob/master/CONTRIBUTING.md)
