### ISSUE TITLE
Make Geojson border configurable

### ISSUE THREAD

**Issue by luizluca** [orchestracities/map-panel#76]
For a large number of shapes, it would be nice to have a way to reduce the shape border.

![image](https://user-images.githubusercontent.com/836788/187306365-40c3bdf2-ce72-4392-9b91-57401cb003b1.png)

**Comment by chicco785** [comment]
indeed the shape size is hardcoded:
https://github.com/orchestracities/map-panel/blob/master/src/layers/data/markersLayer.tsx#L383
